version: '3.9'
services:
  user-db:
    image: postgres:14.1-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=pedaling_user_db
    ports:
      - '5432:5432'
    volumes:
      - db-data-user:/var/lib/postgresql/data

  pedal-db:
    image: postgres:14.1-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=pedaling_pedal_db
    ports:
      - '5433:5432'
    volumes:
      - db-data-pedal:/var/lib/postgresql/data

volumes:
  db-data-user:
    driver: local

  db-data-pedal:
    driver: local
